def PrintMenu():
    print("Your possible options are: ")
    print("1.Add a book")
    print("2.Remove a book")
    print("3.Update a book")
    print("4.List the books")
    print("5.Add a client")
    print("6.Remove a client")
    print("7.Update a client")
    print("8.List the clients")
    print("9.Rent a book")
    print("10.Return a book")
    print("11.Search a book")
    print("12.Search a client")
    print("13.List all rentals")
    print("14.Most rented books")
    print("15.Most active clients")
    print("16.Most rented author")
    print("17.Late rentals")
    print("18.Remove a rental")
    print("19.Undo")
    print("20.Redo")


